# Import

In [1]:
import pandas as pd
import os
import numpy as np 
from sklearn import preprocessing, svm 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn import metrics
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.model_selection import RepeatedKFold
from sklearn.ensemble import IsolationForest
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.metrics import fbeta_score, make_scorer
from sklearn.decomposition import PCA
from keras.datasets import mnist
from matplotlib import pyplot
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler

# Data

In [36]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [34]:
X=[]
for i in range(X_train.shape[0]):
    img=X_train[i]
    img = img.flatten()   
    np_img=np.asarray(img)
    X.append(np_img)

for i in range(X_test.shape[0]):
    img=X_test[i]
    img = img.flatten()   
    np_img=np.asarray(img)
    X.append(np_img)
    
X=pd.DataFrame(X)
print(X.shape)

(70000, 784)


0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   778  779  780  781  782  783  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 784 columns]

In [61]:
Y=pd.concat([pd.DataFrame(y_train),pd.DataFrame(y_test)],axis=0)
Y = np.ravel(Y)
Y=Y==3
Y

array([ True, False, False, ..., False,  True, False])

# Model

In [80]:
scaler = StandardScaler()
model = LogisticRegression()

x_train, x_test, y_train, y_test =train_test_split(X, Y, test_size=0.25, random_state=42)

model.fit(x_train, y_train)
y_pred = model.predict(x_test)
acc=np.sum(y_pred==y_test)/len(y_test)
print("accuracy: " , acc*100 , "%")

accuracy:  92.10285714285715 %


/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [70]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[12656,     5],
       [ 1339,     0]])

# Multiclass

In [76]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()
Y=pd.concat([pd.DataFrame(y_train),pd.DataFrame(y_test)],axis=0)
Y = np.ravel(Y)
Y

array([5, 0, 4, ..., 4, 5, 6], dtype=uint8)

In [77]:
scaler = StandardScaler()
model = LogisticRegression()

x_train, x_test, y_train, y_test =train_test_split(X, Y, test_size=0.2, random_state=0)

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

model.fit(x_train, y_train)
y_pred = model.predict(x_test)
acc=np.sum(y_pred==y_test)/len(y_test)
print("accuracy: " , acc*100 , "%")

accuracy:  90.92857142857143 %


/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
